export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--bg-primary)',
        'bg-card': 'var(--bg-card)',
        'bg-elevated': 'var(--bg-elevated)',
        'brutal-black': 'var(--color-border)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'brutal-mint': 'var(--color-accent)',
        'brutal-purple': '#8338EC',
        'brutal-yellow': '#FFBE0B',
        'brutal-blue': '#4895EF',
        'brutal-orange': '#FB5607',
        'brutal-pink': '#FF006E',
        'brutal-coral': '#FF6B6B',
        'brutal-lavender': '#A388EE',
        'success': 'var(--color-success)',
        'success-text': 'var(--color-success-text)',
        'success-muted': 'var(--color-success-muted)',
        'success-soft': 'var(--color-success-soft)',
        'success-border': 'var(--color-success-border)',
        'error': 'var(--color-error)',
        'error-text': 'var(--color-error-text)',
        'error-muted': 'var(--color-error-muted)',
        'error-soft': 'var(--color-error-soft)',
        'error-border': 'var(--color-error-border)',
        'warning-text': 'var(--color-warning-text)',
        'overlay': 'var(--color-overlay)',
        'border-muted': 'var(--color-border-muted)',
        'correct': 'var(--color-correct)',
        'incorrect': 'var(--color-incorrect)',
        'incorrect-bg': 'var(--color-incorrect-bg)',
        'type-video': 'var(--color-type-video)',
        'type-video-bg': 'var(--color-type-video-bg)',
        'type-book': 'var(--color-type-book)',
        'type-book-bg': 'var(--color-type-book-bg)',
        'type-course': 'var(--color-type-course)',
        'type-course-bg': 'var(--color-type-course-bg)',
        'type-article': 'var(--color-type-article)',
        'type-article-bg': 'var(--color-type-article-bg)',
        'ring-track': 'var(--color-ring-track)',
        'chart-axis': 'var(--color-chart-axis)',
      },
      boxShadow: {
        'brutal-sm': '3px 3px 0px var(--shadow-color)',
        'brutal-md': '4px 4px 0px var(--shadow-color)',
        'brutal-lg': '6px 6px 0px var(--shadow-color)',
      },
      fontFamily: {
        heading: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
