/** @fileoverview Suggested prompts for the AI Tutor, organized by technology */

export const TUTOR_PROMPTS = {
  python: [
    'Explain list comprehensions with examples',
    'What are Python decorators and when should I use them?',
    'How do generators work in Python?',
    'Explain the difference between deepcopy and shallow copy',
    'What are context managers and the "with" statement?',
    'How does async/await work in Python?',
  ],
  cpp: [
    'Explain pointers vs references in C++',
    'What are smart pointers and when to use each type?',
    'How does RAII work in C++?',
    'Explain virtual functions and polymorphism',
    'What are move semantics and rvalue references?',
    'How do templates work in C++?',
  ],
  git: [
    'Explain the difference between merge and rebase',
    'How do I resolve merge conflicts?',
    'What is git stash and when should I use it?',
    'Explain the git branching workflow',
    'How does cherry-pick work?',
    'What is git bisect and how do I use it?',
  ],
  javascript: [
    'Explain the difference between let, const, and var',
    'How does the event loop and call stack work?',
    'What is a closure and where is it useful?',
    'Explain Promise.all vs Promise.race vs Promise.allSettled',
    'What is prototypal inheritance in JavaScript?',
    'How does the "this" keyword work in different contexts?',
  ],
  sql: [
    'Explain INNER JOIN vs LEFT JOIN with examples',
    'When should I use a subquery vs a JOIN?',
    'How do indexes work and when should I add one?',
    'Explain the difference between WHERE and HAVING',
    'What is database normalization and the three normal forms?',
    'How do transactions and ACID properties work?',
  ],
  typescript: [
    'Explain the difference between interface and type alias',
    'When and how should I use generics?',
    'What are utility types like Partial, Pick, and Omit?',
    'Explain union types, intersection types, and discriminated unions',
    'How does TypeScript handle null and undefined?',
    'What is "strictNullChecks" and why does it matter?',
  ],
  react: [
    'When should I use useCallback vs useMemo?',
    'Explain the React reconciliation algorithm',
    'What causes unnecessary re-renders and how do I prevent them?',
    'How does the Context API compare to state management libraries?',
    'Explain the rules of hooks and why they exist',
    'How do I handle side effects properly in useEffect?',
  ],
  nodejs: [
    'How does the Node.js event loop handle async operations?',
    'Explain the difference between CommonJS and ES modules',
    'How do I structure an Express REST API?',
    'What is middleware and how does the Express middleware chain work?',
    'How do I handle errors in async Express routes?',
    'When should I use streams instead of reading files all at once?',
  ],
  java: [
    'Explain the difference between abstract class and interface in Java',
    'How does Java garbage collection work?',
    'What is the Collections framework and when to use each collection?',
    'Explain generics and type erasure in Java',
    'What are Java streams and how do I use them for data processing?',
    'Explain checked vs unchecked exceptions',
  ],
  dsa: [
    'Explain Big-O notation with practical examples',
    'When should I use a HashSet vs a TreeSet?',
    'Explain the two-pointer technique and when to use it',
    'How does merge sort work and what is its time complexity?',
    'Explain DFS vs BFS and when to use each',
    'What is dynamic programming and when does it apply?',
  ],
};
