/** @fileoverview Suggested prompts for the AI Tutor, organized by technology */

export const TUTOR_PROMPTS = {
  python: [
    'Explain list comprehensions with examples',
    'What are Python decorators and when should I use them?',
    'How do generators work in Python?',
    'Explain the difference between deepcopy and shallow copy',
    'What are context managers and the "with" statement?',
    'How does async/await work in Python?',
  ],
  cpp: [
    'Explain pointers vs references in C++',
    'What are smart pointers and when to use each type?',
    'How does RAII work in C++?',
    'Explain virtual functions and polymorphism',
    'What are move semantics and rvalue references?',
    'How do templates work in C++?',
  ],
  git: [
    'Explain the difference between merge and rebase',
    'How do I resolve merge conflicts?',
    'What is git stash and when should I use it?',
    'Explain the git branching workflow',
    'How does cherry-pick work?',
    'What is git bisect and how do I use it?',
  ],
  ue5: [
    'Explain the Actor lifecycle in Unreal Engine 5',
    'When should I use Blueprint vs C++?',
    'How does the Enhanced Input System work?',
    'Explain UE5 component architecture',
    "What are delegates and how to use them?",
    'How does replication work for multiplayer?',
  ],
  blender: [
    'How do I UV unwrap a model properly?',
    'Explain the rigging workflow in Blender',
    'What are modifiers and which ones are most useful?',
    'How do I export models for Unreal Engine?',
    'Explain weight painting for animations',
    'What is the difference between Cycles and Eevee?',
  ],
  pytorch: [
    'Explain tensors and basic operations in PyTorch',
    'How do I build a custom nn.Module?',
    'Explain backpropagation and autograd',
    'What is the DataLoader and how to use it?',
    'How do I save and load models in PyTorch?',
    'Explain CNNs and how to implement one',
  ],
  'rl-ppo': [
    'Explain the PPO algorithm step by step',
    'What is the difference between on-policy and off-policy?',
    'How does the actor-critic architecture work?',
    'Explain the advantage function and GAE',
    'What is the exploration vs exploitation tradeoff?',
    'How does the clipped objective in PPO work?',
  ],
  zeromq: [
    'Explain the REQ-REP pattern in ZeroMQ',
    'When should I use PUB-SUB vs PUSH-PULL?',
    'How does message framing work in ZeroMQ?',
    'Explain the difference between bind and connect',
    'How do I serialize data for ZeroMQ messages?',
    'What is the inproc transport and when to use it?',
  ],
  fastapi: [
    'How do I create REST endpoints with FastAPI?',
    'Explain Pydantic models for request validation',
    'How does dependency injection work in FastAPI?',
    'What is the difference between query and path params?',
    'How do I handle authentication with OAuth2?',
    'Explain async endpoints and when to use them',
  ],
  'federated-learning': [
    'Explain the FedAvg algorithm step by step',
    'What challenges does non-IID data create?',
    'How does differential privacy protect user data?',
    'Explain the client-server architecture in FL',
    'What is client drift and how to mitigate it?',
    'Cross-device vs cross-silo: what are the differences?',
  ],
};
